# serverless.yml

service: dictionary-application

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
          Resource: 'arn:aws:dynamodb:us-east-1:075267662959:table/dictionary'

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
